language: perl
sudo: false

install:
  - perlbrew list
  - sh corpus/install_database_server
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.20"
  - "5.22"

script:
  - dzil test -v

